site: Fascist-Desantis.com
title: Ron DeSantis is a Fascist
greetings: Welcome to Fascist-DeSantis.com 👋
description: >-
  A blog started in response to Jason Brodeur's (R-Lake Mary) [SB 1316](https://www.flsenate.gov/Session/Bill/2023/1316) bill to force any who blogs about the fascist government of Florida register with the fascist government.
lang: en
image: 
timezone:  New York
repo: https://github.com/mgitz/fascist-desantis # site repo [optional]
data-theme: light # default theme "dark" | "light"
discus-identifier: 
default-thumb: 

author:
  name: A concerned Floridian
  url: https://fascist-desantis.com/
  bio: Just a person wondering why the part of "small government" wants to be big brother and control everything I do... 
  avatar: /img/author/fascist-desantis.png
  username: mgitz # general username
  github: mgitz # github username
  twitter: fascist_GovDes # twitter username
  email: mgitz@fascist-desantis.com # email adress

twitter:
  username: fascist_GovDes
  card: summary_large_image

# Font Settings
googlewebfonts: family=Archivo:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://fascist-desantis.com" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug/
  authors:
    output: true
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      image: https://res.cloudinary.com/notee/image/upload/v1640411291/notes/imgseo.jpg
  - 
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"


relative_links:
  enabled:     true
  collections: false


